# Generated by Django 5.2.17 on 2026-08-30 15:07

import apps.events.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, verbose_name='nome do evento')),
                ('summary', models.TextField(max_length=500, verbose_name='descrição resumida')),
                ('sport_category', models.CharField(choices=[('corrida', 'Corrida'), ('trail', 'Trail running'), ('ciclismo', 'Ciclismo'), ('triatlo', 'Triatlo'), ('natacao', 'Natação'), ('caminhada', 'Caminhada'), ('obstaculos', 'Corrida de obstáculos'), ('outro', 'Outra modalidade')], max_length=20, verbose_name='modalidade esportiva')),
                ('event_datetime', models.DateTimeField(verbose_name='data e horário do evento')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='estado')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacidade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='situação')),
                ('cover_image', models.ImageField(blank=True, upload_to='events/covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), apps.events.models.validate_cover_image_size], verbose_name='imagem de capa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'db_table': 'events_event',
                'ordering': ('event_datetime', 'title'),
                'indexes': [models.Index(fields=['organization', 'status', 'event_datetime'], name='event_org_status_date_idx'), models.Index(fields=['status', 'event_datetime'], name='event_public_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_greater_than_zero'), models.CheckConstraint(condition=models.Q(('status__in', ['rascunho', 'publicado', 'cancelado'])), name='event_status_valid')],
            },
        ),
    ]
