# Generated by Django 5.2.17 on 2026-08-31 20:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='events.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'tipo de ingresso',
                'verbose_name_plural': 'tipos de ingresso',
                'db_table': 'events_ticket_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TicketLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome do lote')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('sales_start', models.DateTimeField(verbose_name='início das vendas')),
                ('sales_end', models.DateTimeField(verbose_name='encerramento das vendas')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='events.tickettype', verbose_name='tipo de ingresso')),
            ],
            options={
                'verbose_name': 'lote de ingresso',
                'verbose_name_plural': 'lotes de ingresso',
                'db_table': 'events_ticket_lot',
                'ordering': ('sales_start', 'price', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'is_active'], name='ticket_type_event_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='ticket_type_capacity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('event'), name='ticket_type_name_event_unique'),
        ),
        migrations.AddIndex(
            model_name='ticketlot',
            index=models.Index(fields=['ticket_type', 'is_active'], name='ticket_lot_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketlot',
            index=models.Index(fields=['sales_start', 'sales_end'], name='ticket_lot_sales_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ticket_lot_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='ticketlot',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ticket_lot_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='ticketlot',
            constraint=models.CheckConstraint(condition=models.Q(('sales_start__lt', models.F('sales_end'))), name='ticket_lot_sales_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='ticketlot',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('ticket_type'), name='ticket_lot_name_type_unique'),
        ),
    ]
