# Generated by Django 5.2.17 on 2026-09-18 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(verbose_name='posição no item')),
                ('full_name', models.CharField(blank=True, max_length=160, verbose_name='nome completo')),
                ('document_type', models.CharField(choices=[('cpf', 'CPF'), ('passaporte', 'Passaporte'), ('outro', 'Outro documento')], default='cpf', max_length=20, verbose_name='tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=40, verbose_name='número do documento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do participante')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do participante')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160, verbose_name='contato de emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone de emergência')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='dados concluídos em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='orders.orderitem', verbose_name='item do pedido')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'db_table': 'registrations_registration',
                'ordering': ('order_item', 'position'),
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='reg_position_gt_zero'), models.CheckConstraint(condition=models.Q(('document_type__in', ['cpf', 'passaporte', 'outro'])), name='reg_document_type_valid'), models.UniqueConstraint(fields=('order_item', 'position'), name='reg_item_position_unique'), models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), models.Q(models.Q(('full_name', ''), _negated=True), models.Q(('document_number', ''), _negated=True), ('birth_date__isnull', False)), _connector='OR'), name='reg_completed_data_required')],
            },
        ),
    ]
