# Generated by Django 5.2.17 on 2026-08-30 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='identificador público')),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovação'), ('approved', 'Aprovada'), ('suspended', 'Suspensa')], db_index=True, default='pending', max_length=20, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'db_table': 'organizations_organization',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador')], default='admin', max_length=20, verbose_name='papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization', verbose_name='organização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro da organização',
                'verbose_name_plural': 'membros das organizações',
                'db_table': 'organizations_membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='org_member_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='organization_membership_user_unique')],
            },
        ),
    ]
